---
title: "SP practical 2"
output: html_document
date: '2022-10-15'
---

```{r}
Pone <- function(n, k, strategy, nrep){
  prisoners_num <- c(1:(2*n))
  boxes_num <- c(1:(2*n))

  curr_prisoner_num <- k # initial k: current prisoner number 
  # count the number of the success that a person can find his/her number 
  success_n <- 0
  for (i in 1:nrep){
    # every repeat time change the distribution of the card number
    cards_num <- sample(1:(2*n), 2*n, replace=FALSE)
    
    ## for strategy 1 and strategy2
    if (strategy == 1 || strategy == 2){
      ## strategy 1
      if (strategy==1){
        # 1st open the boxes with their number read the card number in it 
        k <- cards_num[curr_prisoner_num]
      }
      ## strategy 2
      if (strategy==2){
        # starting from a randomly selected box
        # a random box number that he/she will open 
        random_box <- sample(1:(2*n),1)
        # read the card number in this random box
        k <- cards_num[random_box]
      }
      
      # each prisoner has n chances of opening a box
      # n_box_open <- 1 # has already open the box once and record the card number as k
      
      # when the number of boxes he/she open less than n
      # while (n_box_open<=n){
      for (open_times in 1:n)
        # if the card in the box they open is their prisoner number, they success
        if (k == curr_prisoner_num) {
          success_n <- success_n+1
          break;
        }
        # if k is not their prisoner number
        if (k != curr_prisoner_num) {
          # go to box number k, read the card num as new k
          k <- cards_num[k]
          # # count the number of the boxes they have already opened
          # n_box_open <- n_box_open+1
        }
      }
    }
    
    ## for strategy 3
    if (strategy==3){
      # random n box numbers that a person will open
      n_random_box <- sample(boxes_num, n, replace=FALSE)
      # the card number list that contain all card number in the boxes he/she open according to the n_random_box
      select_card_num <- cards_num[n_random_box]
      # if the prison number in the select_card_num list
      # which means one of he/she selected box contian a card with their prison number
      if (curr_prisoner_num %in% select_card_num){
        success_n <- success_n+1
      }
    }
  }
  # estimate the probability of a single prisoner succeeding in finding their number
  prob <- success_n/nrep
  return(prob)
}


# n <- 5         # #prisoner:2n=10
# k <- 7           # prisoner’s number
# strategy <- 2   # strategy=1/2/3 corresponding to strategy 1, 2, and 3
# nrep <- 10000    # the number of replicate simulations to run in order to estimate the probability(10000 is a reasonable default)
# # a test for Pone function
set.seed(100)
prob <- Pone(50, 7, 1, 10000)
prob
system.time(Pone(50, 7, 3, 1000))
```

```{r}
# the probability of all prisoners finding their number
Pall <- function(n, strategy, nrep){
  prob <- 1
  for (prison in prisoners_num){
    # the probability of a single prisoner succeeding in finding their number
    single_prob <- Pone(n, prison, strategy, nrep)
    prob <- prob*single_prob
  }  
  return(prob)
}

n <- 5           # #prisoner:2n=10
strategy <- 3    # strategy=1/2/3 corresponding to strategy 1, 2, and 3
nrep <- 10000    # the number of replicate simulations to run in order to estimate the probability(10000 is a reasonable default)
# a test for Pone function
prob <- Pall(n, strategy, nrep)
prob
```

```{r}
Pall <- function(n, strategy, nrep){
  prisoners_num <- c(1:(2*n))
  boxes_num <- c(1:(2*n))
  success_n <- 0
  for (i in 1:nrep){
    # every repeat time change the card number
    cards_num <- sample(1:(2*n), 2*n, replace=FALSE)
    # print(cards_num)
    
    # count the number of prisoners who are sucessful finding their number
    success_prisoner <- 0
    for (prisoner_num in prisoners_num){
      ## for strategy 1 and strategy2
      if (strategy == 1 || strategy == 2){
        ## strategy 1
        if (strategy==1){
          # 1st open the boxes with their number read the card number in it 
          k <- cards_num[which(boxes_num==prisoner_num)]
        }
        ## strategy 2
        if (strategy==2){
          # starting from a randomly selected box
          # a random box number that he/she will open 
          random_box <- sample(1:(2*n),1)
          # read the card number in this random box
          k <- cards_num[which(boxes_num==random_box)]
        }
        # print('box number:')
        # print(boxes_num[which(boxes_num==curr_prisoner_num)])
        # print('card number:')
        # print(cards_num[which(boxes_num==curr_prisoner_num)])
        # print('--------------')
        # if k is not their prisoner number
        n_box_open <- 1
        # when the number of boxes he open less than n
        while (n_box_open<n){
          if (k == prisoner_num) {
            success_prisoner <- success_prisoner+1
            # print('---------------success------------------')
            break;
          }
          if (k != prisoner_num) {
          # go to box number k, read the card num as new k
          # print('box number:')
          # print(k)
          # print('card number:')
          # print(cards_num[which(boxes_num==k)])
          # print('--------------')
          k <- cards_num[which(boxes_num==k)]
          n_box_open <- n_box_open+1
          }
          # if (n_box_open==n) print('---------------fail------------------')
        }
      }
      
      ## for strategy 3
      if (strategy==3){
        # random n box numbers that a person will open
        n_random_box <- sample(boxes_num, n, replace=FALSE)
        # the card number list that contain all card number in the boxes he/she open according to the n_random_box
        select_card_num <- cards_num[n_random_box]
        # if the prison number in the select_card_num list
        # which means one of he/she selected box contian a card with their prison number
        if (prisoner_num %in% select_card_num){
          success_prisoner <- success_prisoner+1
          # print('---------------success------------------')
        }
      }
    }
    if (success_prisoner == (2*n)) success_n <- success_n + 1
  }
  return(success_n/nrep)
}

Pall(5,3,10000)


```


```{r}
# function implementation example
nrep <- 10000    # the number of replicate simulations to run in order to estimate the probability(10000 is a reasonable default)

## for n= 5
n1 <- 5
## for strategy 1
# individual k=7 success probabilities under strategy 1
n5_individualk_prob_1 <- Pone(n1, 7, 1, nrep); n5_individualk_prob_1
# joint success probabilities under strategy 1
n5_joint_success_prob_1 <- Pall(n1, 1, nrep); n5_joint_success_prob_1

## for strategy 2
# individual k=7 success probabilities under strategy 2
n5_individualk_prob_2 <- Pone(n1, 7, 2, nrep); n5_individualk_prob_2
# joint success probabilities under strategy 2
n5_joint_success_prob_2 <- Pall(n1, 2, nrep); n5_joint_success_prob_2

## for strategy 3
# individual k=7 success probabilities under strategy 3
n5_individualk_prob_3 <- Pone(n1, 7, 3, nrep); n5_individualk_prob_3
# joint success probabilities under strategy 3
n5_joint_success_prob_3 <- Pall(n1, 3, nrep); n5_joint_success_prob_3


## for n= 50
n2 <- 50
## for strategy 1
# individual k=7 success probabilities under strategy 1
n50_individualk_prob_1 <- Pone(n2, 7, 1, nrep); n50_individualk_prob_1
# joint success probabilities under strategy 1
n50_joint_success_prob_1 <- Pall(n2, 1, nrep); n50_joint_success_prob_1

## for strategy 2
# individual k=7 success probabilities under strategy 2
n50_individualk_prob_2 <- Pone(n2, 7, 2, nrep); n50_individualk_prob_2
# joint success probabilities under strategy 2
n50_joint_success_prob_2 <- Pall(n2, 2, nrep); n50_joint_success_prob_2

## for strategy 3
# individual k=7 success probabilities under strategy 3
n50_individualk_prob_3 <- Pone(n2, 7, 3, nrep); n50_individualk_prob_3
# joint success probabilities under strategy 3
n50_joint_success_prob_3 <- Pall(n2, 3, nrep); n50_joint_success_prob_3

```

```{r}
dloop <- function(n, nrep){
  # a list of prisoner number
  prisoners_num <- c(1:(2*n))
  
  # create a list to record the occurrence of the each times
  # e.g. count_l[1] = 10 means there are totally 10 times the prisoner just need to open the first box and succeed.
  count_l <- rep(0,(2*n))
  
  for (i in 1:nrep){
    # every repeat time change the card number
    cards_num <- sample(1:(2*n),2*n,replace=FALSE)
    
    # create a list to record the open times for 2n prisoners
    open_times_l <- rep(0,(2*n))
    for (prisoner in prisoners_num){
      # the card number of the box that s/he first open
      card_number <- cards_num[prisoner]
      # record the loops/times that a person need to find her/his number
      # s/he has already open one box
      open_times <- 1
      # if the card number in the box that s/he first opend is not her/his prisoner number, s/he still need to open until s/he finds her/his prisoner number
      while(card_number != prisoner){
        # new and current box number that s/he will open next
        box_num <- card_number
        # new and current card number that s/he open now
        card_number = cards_num[box_num]
        # add one means s/he open the boxes one more times
        open_times <- open_times+1
      }
      # when a prisoner open (open_times) boxes to find out their prisoner number, add 1 to the count list, which means there is one more times that at least a loop of length (open_times) to find out the number
      open_times_l[prisoner] <- open_times
      # count_l[open_times] <- 1#count_l[open_times]+1
    }
    # print(open_times_l)
    # print(unique(open_times_l))
    count_l[unique(open_times_l)] <- count_l[unique(open_times_l)]+1
  }
  # return(count_l/((2*n)*nrep))
  # print(count_l)
  return(count_l/nrep)
}

# n <- 5
# nrep <- 10000
dloop(5, 3)
system.time(dloop(50, 10000))

```

```{r}
dloop <- function(n, nreps) {
  prisoners <- c(1:(2*n))#sample(1:(2*n), size = 2*n, replace = FALSE)
  count_set = matrix(0, nrow = nreps, ncol = (2*n))
  # zero <- replicate(2*n, 0)
  
  for (i in 1:nreps) {
    card <- sample(1:(2*n), size = 2*n, replace = FALSE)
    # count <- 0
    for (k in prisoners) {
      card_index = vector(length = (2*n))
      card_index[1] = k
      times <- 1
      # check for each prisoner if the first opening time successes
      while (card[card_index[times]] != k){
        card_index[times+1] = card[card_index[times]]
        times <- times + 1
      }
      count_set[i,times] = 1
    }
  }
  # print(colSums(count_set))
  # print(colSums(count_set)/nreps)
  # for (j in count_set) {
  #   zero[j] <- sum(count_set[,j] == 0)
  # }
  # prob <- (nreps - zero)/nreps
  # return (prob)
  return(colSums(count_set)/nreps)
}
dloop(50, 10000)
system.time(dloop(50, 10000))
```


```{r}
# estimate the probabilities for n = 50
prob_l <- dloop(50, 10000)
prob_l
# sum(prob_l[51:100])
```
```{r}
suibian <- function(){
  nrep <- 10000
  # record the number of no loop longer than 50 in a random reshuffling of cards to boxes
  count <- 0
  for (i in 1:nrep){
    loop <- dloop(50, 1)
    if (sum(loop[51:100] == 0) == 50) count <- count+1
  }
  return(count/nrep)
}
system.time(suibian())
```

```{r}
for (i in 1:nreps){
  # every repeat time change the distribution of the card number
  card <- sample(1:(2*n), size = 2*n, replace = FALSE)
  
  # count the number of the success that a person can find his/her number 
  count_success = 0
  
  # create a list containing the index of *card*
  card_index <- vector(length = n)
  
  if (strategy == 1){
    # the first element of *card_index* should be the prisoner’s number
    card_index[1] <- k
      
      # record the number of times of opening a box
      times <- 1 ## has already open the box once and record the card number as k
      # when the number of boxes he/she open less than n
      while (times < n) {
        # check whether the number in *card* equals the prisoner’s number, 
        # if equal, s/he succeeding in finding their number and then break the while loop
        if (card[card_index[times]] == k) {
          count <- count + 1 
          break
        }
        # if the card number is not his/her prisoner number
        else{
          # go to the box which is printed the number as card number he open last times (times)
          # then record the new box number he will open in (times+1) times
          card_index[times+1] = card[card_index[times]]
          # add 1 to the boxes opening times, since s/he has opened one more box
          times = times + 1
        }
      }
    }
    # estimate the probability of a single prisoner (k) succeeding in finding his/her prisoner number
    prob = count/nreps
    return (prob) 
  }
```

```{r}
Pone <- function(n, k, strategy, nreps){
  
  # strategy 1
  if (strategy == 1){
    # count the number of the success that a person can find his/her number 
    count_success = 0
    
    for (i in 1:nreps) {
      # every repeat time change the distribution of the card number
      card <- sample(1:(2*n), size = 2*n, replace = FALSE)
      
      # create a list containing the index of *card*
      card_index <- vector(length = n)
      # the first element of *card_index* should be the prisoner’s number
      card_index[1] <- k
      
      # record the number of times of opening a box
      times <- 1 ## has already open the box once and record the card number as k
      # when the number of boxes he/she open less than n
      while (times < n) {
        # check whether the number in *card* equals the prisoner’s number, 
        # if equal, s/he succeeding in finding their number and then break the while loop
        if (card[card_index[times]] == k) {
          count_success <- count_success + 1 
          break
        }
        # if the card number is not his/her prisoner number
        else{
          # go to the box which is printed the number as card number he open last times (times)
          # then record the new box number he will open in (times+1) times
          card_index[times+1] = card[card_index[times]]
          # add 1 to the boxes opening times, since s/he has opened one more box
          times = times + 1
        }
      }
    }
    # estimate the probability of a single prisoner (k) succeeding in finding his/her prisoner number
    prob = count_success/nreps
    return (prob) 
  }
  
  # strategy 2
  if (strategy == 2){
    count = 0
    
    for (i in 1:nreps) {
      
      card <- sample(1:(2*n), size = 2*n, replace = FALSE)
      card_index = vector(length = n)
      # starting from a randomly selected box
      card_index[1] = sample(1:(2*n), size = 1)
      
      times = 0
      while (times < n) {
        
        if (card[card_index[times+1]] == k) {
          count = count +1 
          break}
        
        else{ 
          card_index[times+2] = card[card_index[times+1]]}
        
        times = times + 1
        
      }}
    
    prob = count/nreps
    return (prob) }
  
  # strategy 3
  if (strategy == 3){
    count = 0
    
    for (i in 1:nreps) {
      card <- sample(1:(2*n), size = 2*n, replace = FALSE)
      card_index <- sample(1:(2*n), size = n, replace = FALSE)
      
      if (k %in% card[card_index]){
        count = count + 1 }
    }
    
    prob = count/nreps
    return (prob)
  } }
```

```{r}
# check a person cannot succeed find their prisoner number after n open times
Success <- function(card_dist, prisoner_num, strategy){
  # strategy 1
  if (strategy == 1){
    # create a list containing the index of *card*
    card_index <- vector(length = n)
    # In strategy 1, the first element of *card_index* should be the prisoner’s number
    card_index[1] <- prisoner_num
    # record the number of times of opening a box
    # initialize the number of times of opening a box
    times <- 0
    
    # when the number of boxes he/she open less than n
    while (times < n) {
      # check whether the number in *card* equals the prisoner’s number, 
      # if equal, s/he succeeding in finding their number and then break the while loop
      if (card_dist[card_index[times+1]] == prisoner_num)  return(TRUE)
      # if the card number is not his/her prisoner number
      else{
        # go to the box which is printed the number as card number he open last times (times)
        # then record the new box number he will open in (times+2) times
        card_index[times+2] = card_dist[card_index[times+1]]
      }
      # add 1 to the boxes opening times, since s/he has opened one more box
      times = times + 1
    }
  }
  # strategy 2
  if (strategy == 2){
    # create a list containing the index of *card*
    card_index <- vector(length = n)
    # In strategy 2, starting from a randomly selected box
    card_index[1] = sample(1:(2*n), size = 1)
    # record the number of times of opening a box
    # initialize the number of times of opening a box
    times <- 0
    
    # when the number of boxes he/she open less than n
    while (times < n) {
      # check whether the number in *card* equals the prisoner’s number, 
      # if equal, s/he succeeding in finding their number and then break the while loop
      if (card_dist[card_index[times+1]] == prisoner_num)  return(TRUE)
      else{
        # go to the box which is printed the number as card number he open last times (times)
        # then record the new box number he will open in (times+2) times
        card_index[times+2] = card_dist[card_index[times+1]]
      }
      # add 1 to the boxes opening times, since s/he has opened one more box
      times = times + 1
    }
  }
  
  #
   # strategy 3
  if (strategy == 3){
    # In strategy 3, the card numbers in the boxes s/he will open is randomly choose n from 1:2n
    card_index <- sample(1:(2*n), size = n, replace = FALSE)
    
    # if the prison number in the card numbers of the boxes (card_index) s/he will open
    # which means one of he/she selected box contain a card with their prison number
    # 
    # add 1 to the count_success, since s/he has succeed in finding her/his number one more times
    if (prisoner_num %in% card_dist[card_index]) return(TRUE)
  }
  else return(FALSE) 
}
```

```{r}
n <- 5
card <- sample(1:(2*n), size = 2*n, replace = FALSE)
if(Success(card,2,1)) print('True')
```

```{r}
Pone <- function(n, k, strategy, nreps){
  # count the number of the success that a person can find his/her number 
  count_success = 0
  for (i in 1:nreps) {
    # every repeat time change the distribution of the card number
    card <- sample(1:(2*n), size = 2*n, replace = FALSE)
    
    if (Success(card,k,strategy)) count_success <- count_success+1
    
    # strategy 1
    if (strategy == 1){
      # create a list containing the index of *card*
      card_index <- vector(length = n)
      # In strategy 1, the first element of *card_index* should be the prisoner’s number
      card_index[1] <- k
      # record the number of times of opening a box
      # initialize the number of times of opening a box
      times <- 0
      
      # when the number of boxes he/she open less than n
      while (times < n) {
        # check whether the number in *card* equals the prisoner’s number, 
        # if equal, s/he succeeding in finding their number and then break the while loop
        if (card[card_index[times+1]] == k) {
          count_success <- count_success + 1 
          break
        }
        # if the card number is not his/her prisoner number
        else{
          # go to the box which is printed the number as card number he open last times (times)
          # then record the new box number he will open in (times+2) times
          card_index[times+2] = card[card_index[times+1]]
        }
        # add 1 to the boxes opening times, since s/he has opened one more box
        times = times + 1
      }
    }
    # strategy 2
    if (strategy == 2){
      # create a list containing the index of *card*
      card_index <- vector(length = n)
      # In strategy 2, starting from a randomly selected box
      card_index[1] = sample(1:(2*n), size = 1)
      # record the number of times of opening a box
      # initialize the number of times of opening a box
      times <- 0
      
      # when the number of boxes he/she open less than n
      while (times < n) {
        # check whether the number in *card* equals the prisoner’s number, 
        # if equal, s/he succeeding in finding their number and then break the while loop
        if (card[card_index[times+1]] == k) {
          # add 1 to the count_success, since s/he has succeed in finding her/his number one more times
          count_success = count_success +1 
          break
        }
        else{
          # go to the box which is printed the number as card number he open last times (times)
          # then record the new box number he will open in (times+2) times
          card_index[times+2] = card[card_index[times+1]]
        }
        # add 1 to the boxes opening times, since s/he has opened one more box
        times = times + 1
      }
    }
    
    # strategy 3
    if (strategy == 3){
      # In strategy 3, the card numbers in the boxes s/he will open is randomly choose n from 1:2n
      card_index <- sample(1:(2*n), size = n, replace = FALSE)
      
      # if the prison number in the card numbers of the boxes (card_index) s/he will open
      # which means one of he/she selected box contain a card with their prison number
      # 
      # add 1 to the count_success, since s/he has succeed in finding her/his number one more times
      if (k %in% card[card_index]) count_success = count_success + 1
    }
  }
  # estimate the probability of a single prisoner (k) succeeding in finding his/her prisoner number
  prob = count_success/nreps
  return (prob)
}


# Function purpose: function 'Pall' is going to estimate the probability of all prisoners finding their number, so that all are released.
# Input: n = half of the number of people (2*n is the total number of prisoners)
#        strategy = 1/2/3 (choose one of strategies you want to investigate from three strategy)
#        nreps = the number of replicate simulations to run in order to estimate the probability (10000 is a reasonable default)
# Output: the estimated probability of all prisoners finding their number, so that all are released, according to nreps repeat times, when using the strategy=1/2/3 .
Pall <- function(n, strategy, nreps){
  # create a prisoners list to record the prisoners number
  prisoners <- sample(1:(2*n), size = 2*n, replace = FALSE)
  
  # count the number of the success that all prisoners finding their number out of nreps
  count_success = 0
  
  for (i in 1:nreps) {
    # every repeat time change the distribution of the card number
    card <- sample(1:(2*n), size = 2*n, replace = FALSE)
    
    for (k in prisoners) {
      # strategy 1
      if (strategy == 1){
        card_index = vector(length = n)
        card_index[1] = k
        times = 0
        while (times < n) {
          
          if (card[card_index[times+1]] == prisoners[k]) {
            count[k] = 1 
            break
          }
          
          else{ 
            card_index[times+2] = card[card_index[times+1]]
          }
          times = times + 1 
        }
      }
    }
    
  }
}





```

